#!/bin/sh
# Refuse a commit when a trailer lists a tool as author.

set -e

msg_file="$1"
[ -f "$msg_file" ] || exit 0

pattern='cursor|claude|chatgpt|openai|anthropic|copilot|gemini|grok|codegen|codex'

if grep -Ei "^[[:space:]]*(Co-authored-by|Signed-off-by):.*($pattern)" "$msg_file" >/dev/null; then
  echo "Refuse this commit: a trailer names a tool as author." >&2
  exit 1
fi

if grep -Ei "^[[:space:]]*(Made-with|Made with Cursor|Generated by|Generated-by)" "$msg_file" >/dev/null; then
  echo "Refuse this commit: a trailer names a tool as author." >&2
  exit 1
fi

exit 0
